git:
  depth: 1
language: c
os: 
  - osx
  - linux
  - windows
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
      - cmake
      - cmake-data
      - mesa-common-dev
      - xorg-dev
      - libasound-dev
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi
before_script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 50; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 50; fi
script:
  - echo $TRAVIS_OS_NAME
  - cmake --version
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then gcc --version; fi
  - python fips clean
    # OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build metal-osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build metal-osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build sapp-metal-osx-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips build sapp-metal-osx-make-release; fi
    # Linux
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build linux-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build sapp-linux-make-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips build sapp-linux-make-release; fi
    # Windows
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build win64-vstudio-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build win64-vstudio-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build d3d11-win64-vstudio-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build d3d11-win64-vstudio-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build sapp-win64-vstudio-debug; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips build sapp-win64-vstudio-release; fi

    # run tests
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then python fips set config osx-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then python fips set config linux-make-release; fi
  - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then python fips set config win64-vstudio-debug; fi
  - python fips run sokol-audio-test
  - python fips run sokol-args-test
  - python fips run sokol-gfx-test

